### ISSUE TITLE
ETAR71FL.ZIP gets parsed and saved as a tibble

### ISSUE THREAD

**Issue by jeffeaton** [OJWatson/rdhs#12]
Not sure why this isn't parsed as standard flat file format, haven't investigated yet. Suspect that the warning message gives a clue to what might be going on.

Code: 
```
cli <- client_dhs(credentials = "~/Documents/Data/DHS/rdhs/credentials",
                  root = "~/Downloads/rdhs-test/")
path <- cli$get_datasets("ETAR71FL.ZIP")
dat <- readRDS(path[[1]])
class(dat)
```
Output:
```
> cli <- client_dhs(credentials = "~/Documents/Data/DHS/rdhs/credentials",
+                      root = "~/Downloads/rdhs-test/")
> path <- cli$get_datasets("ETAR71FL.ZIP")
Logging into DHS website...
Creating Download url list from DHS website...
Logging into DHS website...
Downloading: 
Ethiopia 2016 DHS HIV Test Results Recode Flat ASCII data (.dat)
  |============================================================================================================================================| 100%
Dataset download finished
Warning messages:
1: In if (file_match == 1) { :
  the condition has length > 1 and only the first element will be used
2: In if (file_match == 2) { :
  the condition has length > 1 and only the first element will be used
> dat <- readRDS(path[[1]])
> class(dat)
[1] "tbl_df"     "tbl"        "data.frame"
```

**Comment by OJWatson** [comment]
most likely ETAR71FL.ZIP contains more than one valid dataset file inside the zip. At the moment I just look for one of `file_types <- c("dta","sav","dat","sas7bdat","dbf")` assuming that their zips are correct. Will check it out and most likely put a catch in to just match for the file type we are expecting giving the "FL/SV/DT" etc

**Comment by jeffeaton** [comment]
Thanks, I can check it later too, just making issue to flag it. 

We should make sure identify file extensions with $ in regex. I updated this in `read_dhs_flat()` because `grep(‘\\.DO’,…` was confusing .DO and .DOC. Might be an issue elsewhere in things I’ve coded though.

**Comment by OJWatson** [comment]
has been sorted in #13
