### ISSUE TITLE
Things to attack

### ISSUE THREAD

**Issue by richfitz** [OJWatson/rdhs#42]
* ~no data.table hack~
* ~dplyr comes out (used only a little in vignettes)~
* ~devtools comes out~
* ~`dhs_datasets` and other functions move client to last arg~
* ~`dhs_dataUpdates` and other endpoint wrappers standardise on snake case~
* ~`set_dhs_credentials` gets a corresponding `get_dhs_config` or something that returns how things are configured~

**Comment by richfitz** [comment]
* Possibly unexport read_zipdata
* No need for `:::` in package code

**Comment by richfitz** [comment]
* Spellcheck

**Comment by richfitz** [comment]
* Expand docs in `get_var_labels`

**Comment by richfitz** [comment]
* Examples should not use `:::`
* Don't export `parse_` functions

**Comment by richfitz** [comment]
* get_var_labels becomes longer like all the others sorry @jeffeaton

**Comment by richfitz** [comment]
* Consider a different prefix for the api functions (perhaps `api_` or `dhsapi_`)

**Comment by richfitz** [comment]
In
```
                          output_dir_root=file.path(.rdhs$client$get_root(),
                                                   "datasets"),
```
Move to `NULL` and move logic internally

**Comment by richfitz** [comment]
everywhere with:

```
  check_for_client()
  .rdhs$client$survey_questions(...)
```

we do

```
client <- dhs_client()
client$survey(...)
```

**Comment by richfitz** [comment]
Scope `  Sys.setlocale("LC_ALL", "C") ## !!! TODO`

**Comment by richfitz** [comment]
`spelling::spell_check_package()`

**Comment by richfitz** [comment]
> Each call to a DHS endpoint returns a data.frame by default with all the results available by default. If you wish to return a data.table then you can change the default behaviour by setting the following system environment variable using Sys.setenv("rdhs_DATA_TABLE" = TRUE).

in the vignette needs tweaking (search in general perhaps)

**Comment by richfitz** [comment]
```
query_param_lengths <- lapply(query, length) %>% unlist()
```
is more concisely spelt `lengths(query)`

**Comment by OJWatson** [comment]
All done (except spellcheck)
