### ISSUE TITLE
remove 'reformat = TRUE' option to get_datasets()?

### ISSUE THREAD

**Issue by jeffeaton** [OJWatson/rdhs#44]
Not sure if this is needed anymore now that haven labelled is fully implemented.

**Comment by OJWatson** [comment]
I like reformat.., although admit it's much the same, and label is better. I'm not removing it for the sake of it being more work for me to just remove it. (plus i like and use it still)

**Comment by jeffeaton** [comment]
If users want datasets with labels as character strings, this should be a post-processing step rather than an alternative dataset save, e.g. an extend the functionality of `labelled` with a function `as_character()` that mirrors functionality of `as_factor()`.

On 18 Jul 2018, at 23:09, OJ Watson <notifications@github.com<mailto:notifications@github.com>> wrote:


I like reformat.., although admit it's much the same, and label is better. I'm not removing it for the sake of it being more work for me to just remove it. (plus i like and use it still)

**Comment by OJWatson** [comment]
yeah fair I agree with that, and it shouldn't be that slow to do the conversion each time etc. 
  v.2 though
