### ISSUE TITLE
update rdhs config

### ISSUE THREAD

**Issue by jeffeaton** [OJWatson/rdhs#47]
Add a function `update_rdhs_config()` to change a single argument of an existing config (without blotting the rest of the config) or revise `set_rdhs_config()` to behave this way.

**Comment by OJWatson** [comment]
Yup this seems good. Will get on it.
________________________________

**Comment by OJWatson** [comment]
So the decision to make it have to be `rdhs.json` is simply to make CRAN happy. Ideally we would want to give that argument any possible path, or even better, just save it away for them in the root of the cache. But for the sake of being extra careful concerning the CRAN policy of not writing to anything outside of the temp directory, for the time being it will stay like this. At least until it's accepted by CRAN. 
(It's a silly rule, as loads of CRAN packages vioate, `rappdirs` being the most obvious, but just to be safe).

**Comment by OJWatson** [comment]
sorry for delay - had my end of 2nd year PhD assessment this week so had to finish some things off. 

I like this and think this seems like a better solution. If you have manually created a file rdhs.json by hand then it should be fine to specify that path. I'll put this in

**Comment by OJWatson** [comment]
This is in place now @sakrejda https://github.com/OJWatson/rdhs/commit/f067faef35a4efc03bce618fd9207810d0088935

I'm going to close this for now @jeffeaton and make a new issue with the original request :)
