### ISSUE TITLE
`parse_dcf()` error for NMIR41FL

### ISSUE THREAD

**Issue by jeffeaton** [OJWatson/rdhs#8]
```
> path <- client$get_datasets("NMIR41FL.ZIP")
Logging into DHS website...
Downloading: 
Namibia 2000 DHS Individual Recode Flat ASCII data (.dat)
  |============================================================================================================================================| 100%
Error in names(dat) <- dct$name : 
  'names' attribute [3502] must be the same length as the vector [3498]
In addition: Warning message:
In lapply(values, as.integer) : NAs introduced by coercion
```

**Comment by jeffeaton** [comment]
The issue here was with decimal data types in `parse_sps()`. The parser is updated to handle these now. As a results, the package also now works for Wealth Index (WI) datasets (wahoo!).  

The issue is fixed for these datasets, but keeping it open because we should check the .DCF parser to see how decimal data are handled in that case.  Strategy: search SPS files for regex "\\([0-9]+)\\" and also have a DCF.

**Comment by OJWatson** [comment]
I'll set up the download and check for all flat files tomorrow again to see how it goes.

**Comment by OJWatson** [comment]
This is now a specific test that's run so that we know if any future changes down the line with the flat parsers occur we can validate against this known one. Keeping open until i've finished downloading all flat files...

**Comment by jeffeaton** [comment]
```
> get_datasets("iaar51fl.zip")
Logging into DHS website...
Downloading: 
India 2006 DHS HIV Test Results Recode Flat ASCII data (.dat)
  |============================================================================================================================================| 100%
Error in names(dat) <- dct$name : 
  'names' attribute [9] must be the same length as the vector [8]
> 
```

**Comment by jeffeaton** [comment]
iaar51fl.zip  works fine now. closing.
