### ISSUE TITLE
provide options `rbind_labelled()` to handle missing columns

### ISSUE THREAD

**Issue by jeffeaton** [OJWatson/rdhs#9]
Something better than `Error in `[.data.frame`(X[[i]], ...) : undefined columns selected` this would be nice... Probably should do something like give option to add missing columns, use only columns in all datasets, or fail (more elegantly than it currently does).

**Comment by jeffeaton** [comment]
Another issue with `rbind_labelled()`, throws error if try to apply `haven::as_factor()` to non labelled variable:
```
> dat <- rbind_labelled(datlst, labels=list(v024 = "concatenate"))
Error in UseMethod("as_factor") : 
  no applicable method for 'as_factor' applied to an object of class "c('integer', 'numeric')"
```

**Comment by OJWatson** [comment]
Do we mind though? If the object is not labelled, i.e. if read in with cli$get_datasets(x, reformat=TRUE)` then you shouldn't be setting an argument for labels.

Documentation could be clearer though then about this.

**Comment by jeffeaton** [comment]
Partial matching of attribute names scuppers variable label inheritance of `rbind_labelled()`.  If there is  not "label" attribute but a "labels" attribute, then `attr(x, "label")` will return `attr(x, "labels")`.

Should do two things:
1. Write `rbind_labelled` a bit more carefully to avoid partial matching where we don't want it.
1. Suggest to store variable labels as `attr(x, "varlabel")` rather than `attr(x, "label")`. This might create slight inconsistency with how `haven` stores variable lables, but I think it's better and shouldn't break any of the value label features of haven I don't think (should check).

**Comment by jeffeaton** [comment]
Also `rbind_labelled()` might be dropping variable label if "concatenate".

**Comment by OJWatson** [comment]
bit lost now - where does this crop up as an issue? However, I am not keen with moving away from consistency with haven.

**Comment by OJWatson** [comment]
could you suggest an example of 2 datasets and some variables where this happens and I can address it

**Comment by OJWatson** [comment]
@jeffeaton  I've put a loose wrapper to catch these cases of when you are using non labelled classes. At the moment it is just looking for the label attribute, if not the foreign related attributes etc and if it's not the label then we basically just skip. 

More needs to be done here though to better handle what happens when people add columns, missing columns etc.

If you can put a few use cases here with codes of either bad datasets or missing column variables etc, i'll get to it.

**Comment by OJWatson** [comment]
@jeffeaton if you think this is still an issue let me know, otherwsie will close it.

**Comment by jeffeaton** [comment]
I think that `rbind_labelled()` still needs some work. But can be for v2 work.

On 18 Jul 2018, at 23:10, OJ Watson <notifications@github.com<mailto:notifications@github.com>> wrote:


@jeffeaton<https://github.com/jeffeaton> if you think this is still an issue let me know, otherwsie will close it.
